version: '3.8'
services:
  rabbitmq:
    image: docker.io/rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI: http://localhost:15672 guest/guest
  order-service:
    build: ./order-service
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
  mail-service:
    build: ./mail-service
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq